Occasionally you may want to set parser options or otherwise customize picocli behavior.
This can easily be done via the setter methods on the picocli `CommandLine` object, but the `PicocliRunner` does not expose that object.

In such cases, you may want to invoke picocli directly instead of using the `PicocliRunner`.
The code below demonstrates how to do this:

.Example of customizing the picocli parser before invoking a command
[source,java]
----
import io.micronaut.configuration.picocli.MicronautFactory;
import io.micronaut.context.ApplicationContext;
import io.micronaut.context.env.Environment;
import picocli.CommandLine;
import picocli.CommandLine.*;
import java.util.concurrent.Callable;

@Command(name = "configuration-example")
class ConfigDemo implements Callable<Object> {

    private static int execute(Class<?> clazz, String[] args) {
        try (ApplicationContext context = ApplicationContext.build(
                clazz, Environment.CLI).start()) { // <1>

            return new CommandLine(clazz, new MicronautFactory(context)). // <2>
                 setCaseInsensitiveEnumValuesAllowed(true). // <3>
                 setUsageHelpAutoWidth(true). // <4>
                 execute(args); // <5>
        }
    }

    public static void main(String[] args) {
        int exitCode = execute(ConfigDemo.class, args);
        System.exit(exitCode); // <6>
    }
    // ...
}
----
<1> Instantiate a new `ApplicationContext` for the `CLI` environment, in a try-with-resources statements, so that the context is automatically closed before the method returns.
<2> Pass a `MicronautFactory` with the application context to the picocli `CommandLine` constructor. This enables dependencies to be injected into the command and subcommands.
<3> An example of configuring the picocli command line parser.
<4> An example of configuring the picocli usage help message.
<5> Execute the command and return the result (this closes the application context).
<6> Optionally call `System.exit` with the returned exit code.