To create a project with picocli support using the Micronaut CLI, use the `create-cli-app` command.
This will add the dependencies for the `picocli` feature, and set the `applicationType` of the generated project to `cli`, so the `create-command` command is available to generate additional commands.

The main class of the project is set to the `*Command` class (based on the project name - e.g., `hello-world` will generate `HelloWorldCommand`):

----
$ mn create-cli-app my-cli-app
----

The generated command looks like this:

.my.cli.app.MyCliAppCommand.java generated by `create-cli-app`

snippet::io.micronaut.picocli.docs.cli.app.MyCliAppCommand[tags="imports,class"]

<1> The picocli link:https://picocli.info/apidocs/picocli/CommandLine.Command.html[@Command] annotation designates this class as a command. The `mixinStandardHelpOptions` attribute adds `--help` and `--version` options to it.
<2> By implementing `Runnable` or `Callable` your application can be executed in a single line (<4>) and picocli takes care of handling invalid input and requests for usage help (`<cmd> --help`) or version information (`<cmd> --version`).
<3> An example option. Options can have any name and be of https://picocli.info/#_strongly_typed_everything[any type]. The generated code contains this example boolean flag option that lets the user request more verbose output.
<4> `PicocliRunner` lets picocli-based applications leverage the Micronaut DI container. `PicocliRunner.run` first creates an instance of this command with all services and resources injected, then parses the command line, while taking care of handling invalid input and requests for usage help or version information, and finally invokes the `run` method.
<5> Put the business logic of the application in the `run` or `call` method.


=== Running the Application

Now you can build the project and start the application. https://guides.micronaut.io/latest/executable-jar.html[Generate an executable Jar]. When you run this JAR, it executes the `MyCliAppCommand` command.

With Gradle:

[source, bash]
----
$ ./gradlew shadowJar
$ java -jar build/libs/my-cli-app-0.1-all.jar -v
----

With Maven Package:

[source, bash]
----
$ ./mvnw package
$ java -jar target/my-cli-app-0.1.jar -v
----
