To add support for Picocli to an existing project, you should first add the picocli dependency and the Micronaut picocli configuration to your build configuration.

dependency:micronaut-picocli[groupId="io.micronaut.picocli"]

The `picocli-codegen` module includes an annotation processor that can build a model from the picocli annotations at compile time rather than at runtime. Enabling this annotation processor in your project is optional, but https://picocli.info/#_annotation_processor[recommended].

dependency:picocli-codegen[scope="annotationProcessor", groupId="info.picocli"]

NOTE: The `picocli-codegen` annotation processor is incompatible with the _Kotlin KSP_ compiler plugin. Using it in a Kotlin project requires the _Kotlin Kapt_ compiler plugin instead. For more information see link:https://github.com/remkop/picocli/issues/1564[KSP support for Kotlin?]

=== Configuring picocli

Picocli does not require configuration. See other sections of the manual for configuring the services and resources to inject.


