To add support for Picocli to an existing project, you should first add the picocli dependency and the Micronaut picocli configuration to your build configuration.

dependency:micronaut-picocli[groupId="io.micronaut.picocli"]

The `picocli-codegen` module includes an annotation processor that can build a model from the picocli annotations at compile time rather than at runtime. Enabling this annotation processor in your project is optional, but https://picocli.info/#_annotation_processor[recommended].

dependency:picocli-codegen[scope="annotationProcessor", groupId="info.picocli"]

NOTE: The https://github.com/remkop/picocli/issues/1564[`picocli-codegen` annotation processor is incompatible with the _Kotlin KSP_ compiler plugin]. For Kotlin with the _KAPT_ plugin, add the `picocli-codegen` dependency in https://docs.micronaut.io/4.4.3/guide/#kapt[kapt scope], and for Groovy add `picocli-codegen` in compileOnly scope.

=== Configuring picocli

Picocli does not require configuration. See other sections of the manual for configuring the services and resources to inject.


