plugins {
    id "io.micronaut.build.internal.picocli-base"
    id "io.micronaut.build.internal.java-base"
}

dependencies {
    testImplementation projects.micronautPicocli
    testImplementation libs.managed.picocli

    testImplementation mn.micronaut.http.client
    testImplementation mn.micronaut.jackson.databind

    testRuntimeOnly mnTest.junit.jupiter.engine
    testRuntimeOnly mnLogging.logback.classic
    testRuntimeOnly mnTest.junit.platform.launcher
}

tasks.withType(Test) {
    useJUnitPlatform()
}
