plugins {
    id 'java'
    id 'io.micronaut.build.internal.picocli-testsuite'
}

dependencies {
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mnTest.junit.jupiter.api)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
