[versions]
micronaut = "5.0.0-M2"
managed-picocli = "4.7.7"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-picocli = { module = "info.picocli:picocli", version.ref = "managed-picocli" }
managed-picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "managed-picocli" }
