[versions]
micronaut = "4.0.0-M1"
managed-picocli = "4.7.2"

micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.10"
spock = "2.3-groovy-4.0"

[libraries]
managed-picocli = { module = "info.picocli:picocli", version.ref = "managed-picocli" }
managed-picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "managed-picocli" }
